### ISSUE TITLE
Pastebin Custom Search Provider

### ISSUE THREAD

**Issue by diegosouzapc** [nkleck/Scumblr_Security_Tool#1]
Hello

I wonder what the configuration file to insert the API key the Pastebin.

Not found in the file scumblr. rb

Could you help me?

I should like also to congratulate the information available.

Best regards

**Comment by nkleck** [comment]
Thats an excellent question.

so the way it works with pastebin is you need to purchase their lifetime Pro account in order to do do scraping. They usually have deals and you can get it for $49, and its good forever. Now once you have the account, you simply whitelist the IP address of your scumblr box within the pastebin site here: http://pastebin.com/api_scraping_faq 

There is no need to add your pastebin api key to the scumblr.rb file. Pastebin will recognize traffic from your server running scumblr as belonging to the pro account and allow that IP to make the queries. Please see the attached image as an example. Obviously ive removed my IP from the image, but that is where you would type in your IP. 

<img width="1034" alt="pastebin_scrape" src="https://cloud.githubusercontent.com/assets/10408319/18752917/e41e443a-80b1-11e6-865e-c6b2c97af2ba.png">

Please let me know if you have any further questions.

**Comment by diegosouzapc** [comment]
Thank you very much for the reply, I bought the lifetime plan and added my IP.
However, I have no success in search result.
The searches are not bringing any results, is there some sort of search operator?
As: AND *. "" etc.?

Thanks for the help

2016-09-22T12:07:23Z 5979 TID-og3es SearchRunner JID-bec5384b345e26d59792d7d8 WARN: Task da75a097a9d06ad93b346277 complete
2016-09-22T12:07:24Z 5979 TID-og3es SearchRunner JID-bec5384b345e26d59792d7d8 INFO: done: 19.925 sec

**Comment by nkleck** [comment]
it looks like the job ran without any issues. I'm currently not on a network i can check the config settings of my scumblr box, so i will verify tonight. In the meantime, can you try creating a pastebin search for something very recently posted to pastebin and then click run search within scumblr. The query defaults to the last 50 posts, and is set to run every hour (i believe). I modified the time i run queries to every 10 minutes (i think, again i'll confirm tonight). try changing the max search field to 500, and click 'run search'. then, when it queries pastbin, it will pull the last 500 posts. 

the query is a plain old string. no boolean involved. one of my future projects is to try incorporating some sort of logic into the search queries.

**Comment by diegosouzapc** [comment]
Thanks for the help, I will continue testing. If you can send your search settings so I can compare.

Best regards

**Comment by nkleck** [comment]
Thanks, are you running sketchy as well?
Also, can you also check if you are behind a network firewall, as well as any iptables or ufw settings on your server that could be preventing a connection? also, you can verify that you can access pastebin's scraping api by doing a wget on your server for  http://pastebin.com/api_scrape_item.php?i=uVTHB9K5

thats some random recent post i just found on pastebin. if your wget returns a the results, you dont have a network problem. it may also return "THIS IP: xxx.xxx.xxx.xxx DOES NOT HAVE ACCESS. CONTACT ADMIN@PASTEBIN.COM TO GET ACCESS!" which means the ip of your scumblr box might not be the same IP pastebin is seeing. 

i'll check my searchprovider script as well as the timing settings per search tonight. if you are running sketchy, there are some steps that i'll share if you need to do a reboot on your server, as it doesnt restart correctly and you need to rebuilt the temporary db sketchy uses.

**Comment by diegosouzapc** [comment]
Hello, I haven't done the integrates of the Sketchy

(Scumblr) -  Pastebin Custom Search Provider:
I was able to get results as follows:
I created a test file within the pastebin and I did the search on scumblr, I've had success.

He just search what I create from today, and he's not bringing things repeated, what he has already identified some time, never appears in search results or in the log.

Within the scumblr. rb there is the following configuration:

. pastebin_api_dev_key = ' xxxxxxxxxxxxxxxxxxxxxx '
. pastebin_api_user_key = ''
. pastebin_api_results_limit = ' 500 '
. pastebin_api_option = ' list '

in config. pastebin_api_option, I've changed to "trends" and the result was the same.

**Comment by diegosouzapc** [comment]
Good morning

I'll wait for your configuration to compare with mine.

Thanks for the help

**Comment by nkleck** [comment]
i do not have any pastebin listed in my scumblr.rb file. 

attached is my lib/tasks/sync_tasks.rake file. you can see i changed the sleep timer to 10 minutes. attached is also a partial output of my crontab -e. 

you can see that i am running the searches every 20 minutes. ive timed my searches and this is plenty of time to complete many searches. I have 32 searches created and they take approximately 8 minutes to complete. so every 20 minutes, the cron job starts the searches, they complete in ~8 minutes, then 2 minutes later (10 minutes after the cron job), sketchy grabs the screenshots. 

being that you were able to successfully test Scumblr and it grabbed your pastebin post. I think the issue is solved. I recommend trying it without the pastebin keys in the scumblr.rb file as it should work. 

that brings us to another painful operation. When you need to do a restart on your server, sketchy can be difficult to start again since it tries to find a db file that may no longer be present (it houses the db file in /tmp, which is deleted every reboot). this has no impact on data storage because the db is only used for the searches it is currently working on. Once it completes its searches, and Scumblr grabs the data, the info in the db is no longer necessary. Scumblr just keeps the location of the screenshots, which is in sketcky/files dir. 

so if you are going to use sketchy, here is how i recommend restarting sketchy and scumblr after a reboot or after you have stopped both jobs. 

sketchy db will need deleted and rebuilt
remove old db (if present)
$ rm /tmp/sketchy-db.db
$ cd sketchy
$ sudo python setup.py install (this only needs ran the first time, after that you can go straight to next command)

Create the Database and Models
$ python manage.py create_db

START SKETCHY
$ sudo -s
$ cd /path/to/sketchy
$ source sketchenv/bin/activate
$ cd /path/to/sketchy/supervisor
$ supervisord -c supervisord.ini

see logging:
$ tail -f supervisor/supervisor.log

START SCUMBLR
These work, but the middle one (logging) might not be working:

nohup redis-server </dev/null &>/dev/null & 
../.rbenv/shims/bundle exec sidekiq -d -l log/sidekiq.log & nohup ../.rbenv/shims/bundle exec rails s </dev/null &>/dev/null &

TESTING IT STARTED
scumblr in browser:
http://your server ip:3000/

try from the server:
wget http://127.0.0.1:8000/api/v1.0/capture

if you get a [] or actual search result, everything is operational. 

A note on your last point about repeated things. I believe scumblr remembers results from previous searches, and if a result is found again in a current search, it ignores it and does not report it to search results. so scumblr will only hit on a result once. 

[scumblr.rb.txt](https://github.com/nkleck/Scumblr_Security_Tool/files/490541/scumblr.rb.txt)
[sync_tasks.rake.txt](https://github.com/nkleck/Scumblr_Security_Tool/files/490542/sync_tasks.rake.txt)
[crontab.txt](https://github.com/nkleck/Scumblr_Security_Tool/files/490543/crontab.txt)
